apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sovcom-api
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
          app: chat
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGIN
              value: http://localhost:8080
            - name: DB_PASSWORD
              valueFrom:
                  configMapKeyRef:
                      name: db-configs
                      key: pg-pass
            - name: DB_USERNAME
              valueFrom:
                  configMapKeyRef:
                      name: db-configs
                      key: pg-user
            - name: GRPC_PORT
              valueFrom:
                  configMapKeyRef:
                      name: backend-conf
                      key: chat-grpc-port
            - name: ISSUER
              valueFrom:
                  configMapKeyRef:
                      name: backend-conf
                      key: issuer-url
            - name: PORT
              valueFrom:
                  configMapKeyRef:
                      name: backend-conf
                      key: chat-port
            - name: POSTGRESDB_URL
              valueFrom:
                  configMapKeyRef:
                      name: db-configs
                      key: pg-chat
            - name: USERS_ADDR
              valueFrom:
                  configMapKeyRef:
                      name: backend-conf
                      key: users-grpc-addr
          image: garrowd/chatservice:1.0.0
          name: chat
          ports:
            - name: grpc
              containerPort: 7081
              hostPort: 7081
            - name: http
              containerPort: 8081
              hostPort: 8081
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    namespace: sovcom-api
    name: chat-service
spec:
    ports:
        - name: grpc
          port: 7081
          targetPort: 7081
        - name: http
          port: 8081
          targetPort: 8081
    selector:
        app: chat
