apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sovcom-api
  name: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGIN
              value: http://localhost:8080
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: pg-pass
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: pg-user
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-conf
                  key: schedule-grpc-port
            - name: ISSUER
              valueFrom:
                configMapKeyRef:
                  name: backend-conf
                  key: issuer-url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-conf
                  key: schedule-port
            - name: POSTGRESDB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-configs
                  key: pg-schedule
          image: garrowd/scheduleattendanceservice:1.0.0
          name: schedule
          ports:
            - name: grpc
              containerPort: 7079
              hostPort: 7079
            - name: http
              containerPort: 8079
              hostPort: 8079
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: sovcom-api
  name: schedule-service
spec:
  ports:
    - name: grpc
      port: 7079
      targetPort: 7079
    - name: http
      port: 8079
      targetPort: 8079
  selector:
    app: schedule
