apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    namespace: sovcom-api
    name: ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    ingressClassName: nginx
    tls:
        - hosts:
           - sovcomstudents.ru
          secretName: sovcom-tls
    rules:
        - host: sovcomstudents.ru
          http:
            paths:
            -   path: /api/users(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: user-service
                        port:
                            name: http
            -   path: /api/admission(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: admission-service
                        port:
                            name: http
            -   path: /api/chat(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: chat-service
                        port:
                            name: http
            -   path: /api/course(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: course-service
                        port:
                            name: http
            -   path: /api/news(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: news-service
                        port:
                            name: http
            -   path: /api/schedule(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: schedule-service
                        port:
                            name: http
            -   path: /api/storage(/|$)(.*)
                pathType: Prefix
                backend:
                    service:
                        name: storage-service
                        port:
                            name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: oauth2-proxy
    namespace: sovcom-api
spec:
    ingressClassName: nginx
    tls:
        - hosts:
          - auth.sovcomstudents.ru
          secretName: sovcom-auth-tls
    rules:
        - host: auth.sovcomstudents.ru
          http:
              paths:
                  -   path: /
                      pathType: Prefix
                      backend:
                          service:
                              name: auth-server-service
                              port:
                                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: dashboard-ingress
    namespace: kubernetes-dashboard
spec:
    ingressClassName: nginx

    rules:
        - host: dashboard.sovcomstudents.ru
          http:
              paths:
                  -   path: /
                      pathType: Prefix
                      backend:
                          service:
                              name: kubernetes-dashboard
                              port:
                                  number: 80