apiVersion: v1
kind: ConfigMap
metadata:
    namespace: sovcom-api
    name: backend-conf
data:
    issuer-url: "http://auth-server-service:9000"

    admission-grpc-port: "7077"
    chat-grpc-port: "7081"
    course-grpc-port: "7090"
    schedule-grpc-port: "7079"
    users-grpc-port: "7082"

    admission-port: "8077"
    auth-port: "9000"
    chat-port: "8081"
    course-port: "8090"
    news-port: "8078"
    schedule-port: "8079"
    storage-port: "8084"
    users-port: "8082"


    auth-redirect-uri: "https://sovcomstudents.ru/authorized"
    storage-server-url: "https://sovcomstudents.ru/api/storage"

    users-grpc-addr: "dns:///user-service:7082"
    academic-grpc-addr: "dns:///schedule-service:7079"
    course-grpc-addr: "dns:///course-service:7090"

  